# Картографическая генерализация {#map-generalize}

## Исходные данные {#map-generalize-initial-data}

[Бланк задания](){target="_blank"}

[База данных](){target="_blank"}

## Приёмы генерализации {#map-generalize-methods}
[В начало справки ⇡](#map-generalize)

Все приёмы генерализации по К.А. Салищеву [[Салищев, 1982](https://yadi.sk/i/e9gW1TmzdEUQqg){target="_blank"}] применительно к геоинформационному ПО можно разделить с точки зрения работы пользователя. Часть приёмов подразумевает, что пользователь при генерализации редактирует геометрию (правит векторную составляющу, работает с узлами), другая часть подразумевает работу с атрибутами объектов, либо вообще – создание нового абсолютно нового класса объектов, зачастую – другого типа геометрии.

Приём генерализации                     |Работа с геометрией|Работа с атрибутами|Изменение типа геометрии
----------------------------------------|-------------------|-------------------|------------------------
`Упрощение`                             |**+**              |**-**              |**-**
`Объединение`                           |**+**              |**-**              |**-**
`Сдвиг`                                 |**+**              |**-**              |**-**
`Утрирование`                           |**+**              |**-**              |**-**
`Отбор`                                 |**-**              |**+**              |**-**
`Обобщение качественных характеристик`  |**-**              |**+**              |**-**
`Обобщение количественных характеристик`|**-**              |**+**              |**-**
`Переход от простых понятий к сложным`  |**-**              |**-**              |**+**




----
_Карпачевский А.М._ **Картография: практикум в QGIS**. М.: Географический факультет МГУ, `r lubridate::year(Sys.Date())`.
----